# バージョン情報
## V0.0
   
   1                      id  : 顧客ID : int64   
   2                     Age  : 顧客の年齢 : str   
   3           TypeofContact  : 顧客への連絡・接触方法 : str   
   4                CityTier  : 都市層(1>2>3) : int64   
   5         DurationOfPitch  : 営業担当者による顧客への商品のセールス時間 : str   
   6              Occupation  : 顧客の職業 : str   
   7                  Gender  : 顧客の性別 : str   
   8  NumberOfPersonVisiting  : 予定している旅行の同行者の数	 : int64   
   9       NumberOfFollowups  : セールス後に営業担当者が行ったフォローアップの回数 : float64   
   10          ProductPitched : 営業担当者のセールスした商品の種類 : str   
   11   PreferredPropertyStar : 顧客の希望するホテルのランク : float64   
   12           NumberOfTrips : 顧客の年間旅行数 : str   
   13                Passport : パスポートの所持(0: 不所持、1: 所持) : int64   
   14  PitchSatisfactionScore : 営業担当者のセールストークに対する顧客の満足度 : int64   
   15             Designation : 顧客の役職 : str   
   16           MonthlyIncome : 顧客の月収 : str   
   17           customer_info : 顧客の情報のメモ(婚姻状況や車の有無、旅行への子どもの同伴の有無) : str

# ライブラリインポート

In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import lightgbm as lgb

# データ加工

In [97]:
def df_Data_Cleansing(df):
    
    return df

In [98]:
df = df_Data_Cleansing(pd.read_csv('data/train.csv',encoding="utf-8")) 
df_test = df_Data_Cleansing(pd.read_csv('data/test.csv',encoding="utf-8"))

# 特徴量追加分

# 学習データ

In [99]:
df

,id,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,Designation,MonthlyIncome,customer_info,ProdTaken
0,0,50歳,Self Enquiry,2,900秒,Large Business,male,1.0,4.0,Basic,3.0,5,1,4,Executive,253905.0,未婚 車未所持 子供なし,1
1,1,56歳,Company Invited,1,14分,Salaried,Male,1.0,4.0,Standard,3.0,2,1,4,Senior Manager,404475.0,"離婚済み,車あり,子供無し",0
2,2,NaN,Self Enquiry,1,10分,Large Business,Female,1.0,3.0,Basic,3.0,4,0,4,Executive,278145.0,"結婚済み、自動車未所有,子供なし",1
3,3,三十七歳,Self Enquiry,2,1080秒,Small Business,female,1.0,3.0,Standard,4.0,1,0,5,Senior Manager,326805.0,離婚済み、車所持、子供無し,0
4,4,48歳,Company Invited,3,1020秒,Small Business,female,1.0,3.0,Basic,4.0,4,0,4,Executive,258435.0,独身／車所持／無子,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3484,3484,40歳,Self Enquiry,2,1560秒,Salaried,Male,2.0,3.0,Basic,3.0,3,0,1,Executive,258900.0,離婚済み 乗用車所持 子供なし,1
3485,3485,40代,Self Enquiry,1,9分,Large Business,Male,3.0,3.0,Basic,5.0,5,0,3,Executive,260415.0,結婚済み、車所持、子供2人,0
3486,3486,31歳,Self Enquiry,1,840秒,Small Business,FEMALE,3.0,2.0,Standard,3.0,5,0,4,Senior Manager,317340.0,独身／車所持／こども1人,0
3487,3487,56歳,Company Invited,2,900秒,Salaried,Male,3.0,6.0,King,3.0,7,1,4,VP,527910.0,結婚済み、自動車未所有、子供2人,1
3488,3488,42歳,Self Enquiry,1,9分,Small Business,male,3.0,1.0,Basic,3.0,3,0,1,Executive,278190.0,"結婚済み,車未所持、子供1人",0

# テストデータ

In [100]:
df_test

,id,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,Designation,MonthlyIncome,customer_info
0,3489,４８歳,Self Enquiry,2,13分,Small Business,Male,1.0,4.0,Super De|uxe,3.0,7,0,3,AVP,496950.0,結婚済み 車所持 子供なし
1,3490,30代,Self Enquiry,2,12分,Small Business,Ｆｅｍａｌｅ,1.0,4.0,Standard,3.0,4,1,3,Senior Manager,月収30.0万円,結婚済み、車未所持、子供なし
2,3491,25歳,Self Enquiry,1,540秒,Salaried,Female,1.0,4.0,Basic,3.0,1,0,3,Executive,月収26.0万円,離婚済み、自動車未所有、子供なし
3,3492,21歳,Company Invited,2,420秒,Salaried,Male,1.0,4.0,Basic,4.0,1,0,3,Senior Manager,259875.0,離婚済み、自動車所有、子供なし
4,3493,41歳,Company Invited,1,7分,Salaried,MALE,1.0,4.0,Basic,3.0,1,0,4,Executive,268830.0,独身/車所持／子供なし
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3484,6973,41歳,Company Invited,1,14分,Small Business,Female,1.0,3.0,Basic,3.0,2,0,4,Executive,261840.0,結婚済み/車なし／子供無し
3485,6974,44歳,Company Invited,1,35分,Salaried,Male,3.0,5.0,Deluxe,3.0,3,0,3,Manager,349770.0,結婚済み、自家用車あり、子供1人
3486,6975,24歳,Self Enquiry,2,21分,Small Business,male,2.0,3.0,basic,3.0,2,0,3,Executive,月収27.0万円,独身、車未所持、子供なし
3487,6976,25歳,Self Enquiry,1,9分,Small Business,MALE,2.0,3.0,Basic,3.0,2,0,3,Executive,272430.0,結婚済み、車未所持、こども1人
3488,6977,44才,Self Enquiry,1,480秒,Small Business,female,4.0,4.0,Deluxe,3.0,5,0,1,Manager,411795.0,未婚 車なし 子供3人

# 学習

In [101]:
y = df["ProdTaken"]
x = df.drop(columns=["ProdTaken", "id"])

cat_cols = x.select_dtypes(include=['object','str']).columns #データの中から「文字列（objectやstr）」の列をすべて探し出す
x[cat_cols] = x[cat_cols].astype('category') # 2行目：探し出した列を、まとめて一括で「category型」に変換する

x

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,Designation,MonthlyIncome,customer_info
0,50歳,Self Enquiry,2,900秒,Large Business,male,1.0,4.0,Basic,3.0,5,1,4,Executive,253905.0,未婚 車未所持 子供なし
1,56歳,Company Invited,1,14分,Salaried,Male,1.0,4.0,Standard,3.0,2,1,4,Senior Manager,404475.0,"離婚済み,車あり,子供無し"
2,NaN,Self Enquiry,1,10分,Large Business,Female,1.0,3.0,Basic,3.0,4,0,4,Executive,278145.0,"結婚済み、自動車未所有,子供なし"
3,三十七歳,Self Enquiry,2,1080秒,Small Business,female,1.0,3.0,Standard,4.0,1,0,5,Senior Manager,326805.0,離婚済み、車所持、子供無し
4,48歳,Company Invited,3,1020秒,Small Business,female,1.0,3.0,Basic,4.0,4,0,4,Executive,258435.0,独身／車所持／無子
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3484,40歳,Self Enquiry,2,1560秒,Salaried,Male,2.0,3.0,Basic,3.0,3,0,1,Executive,258900.0,離婚済み 乗用車所持 子供なし
3485,40代,Self Enquiry,1,9分,Large Business,Male,3.0,3.0,Basic,5.0,5,0,3,Executive,260415.0,結婚済み、車所持、子供2人
3486,31歳,Self Enquiry,1,840秒,Small Business,FEMALE,3.0,2.0,Standard,3.0,5,0,4,Senior Manager,317340.0,独身／車所持／こども1人
3487,56歳,Company Invited,2,900秒,Salaried,Male,3.0,6.0,King,3.0,7,1,4,VP,527910.0,結婚済み、自動車未所有、子供2人
3488,42歳,Self Enquiry,1,9分,Small Business,male,3.0,1.0,Basic,3.0,3,0,1,Executive,278190.0,"結婚済み,車未所持、子供1人"

In [102]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42)

train_data = lgb.Dataset(x_train,label=y_train)
params = {
    'objective': 'binary',
    'boosting_type': 'gbdt',
    'metric': 'binary_logloss',
    'num_leaves': 31,
    'learning_rate': 0.05    
}

model = lgb.train(params, train_data,num_boost_round=100)

[LightGBM] [Info] Number of positive: 406, number of negative: 2385
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000194 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 629
[LightGBM] [Info] Number of data points in the train set: 2791, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.145468 -> initscore=-1.770601
[LightGBM] [Info] Start training from score -1.770601

In [103]:
y_pred_proba = model.predict(x_test)
y_pred_proba

array([0.09787009, 0.0163107 , 0.03657699, 0.52144748, 0.09293765,
       0.02349998, 0.02163631, 0.59291142, 0.0093335 , 0.01006859,
       0.09960325, 0.02080546, 0.03679968, 0.04719475, 0.53562289,
       0.42630783, 0.05528819, 0.05186173, 0.38851911, 0.22347973,
       0.01744253, 0.17487105, 0.00448279, 0.17175414, 0.02006072,
       0.38939618, 0.10851453, 0.19368848, 0.04786596, 0.07798606,
       0.02211192, 0.2350681 , 0.51128761, 0.21524235, 0.09818221,
       0.25824529, 0.05746747, 0.01236421, 0.02422261, 0.4307234 ,
       0.21825942, 0.63813042, 0.01189806, 0.09506048, 0.10428969,
       0.33911716, 0.02473002, 0.08611342, 0.05170188, 0.4150715 ,
       0.06625506, 0.01490425, 0.02512185, 0.06462217, 0.19462862,
       0.02376788, 0.01430835, 0.08352592, 0.01280533, 0.5366505 ,
       0.094147  , 0.09602201, 0.03427107, 0.05588228, 0.4939943 ,
       0.09534983, 0.01266233, 0.12305455, 0.31459722, 0.01887202,
       0.03390191, 0.0568461 , 0.07848587, 0.02662083, 0.01598145,
       0.09945461, 0.22336085, 0.04059535, 0.00786223, 0.13434542,
       0.00938025, 0.42246417, 0.04163135, 0.32188973, 0.1071678 ,
       0.72505111, 0.01693082, 0.23749518, 0.01856939, 0.01578168,
       0.01248166, 0.23898677, 0.7863421 , 0.03446315, 0.07944512,
       0.14653401, 0.09548916, 0.23042223, 0.04769315, 0.10492365,
       0.4753244 , 0.03100636, 0.03525271, 0.39778078, 0.05170703,
       0.03784968, 0.016646  , 0.2649863 , 0.01027859, 0.44629862,
       0.0146663 , 0.54052744, 0.01294031, 0.05483927, 0.01623276,
       0.21965599, 0.01070408, 0.03004939, 0.24397376, 0.04049193,
       0.13891867, 0.26825217, 0.05808239, 0.0376834 , 0.02152099,
       0.14446364, 0.03583368, 0.05618964, 0.02109474, 0.15117933,
       0.12982934, 0.0484677 , 0.14171328, 0.04263484, 0.25499138,
       0.01709339, 0.0291964 , 0.15292028, 0.24749548, 0.01137413,
       0.07426341, 0.06984121, 0.0196176 , 0.01341053, 0.26942655,
       0.65814231, 0.04626758, 0.06770242, 0.01773899, 0.12875579,
       0.84747395, 0.10166034, 0.04060822, 0.03537241, 0.05321806,
       0.03898148, 0.01232635, 0.38889934, 0.07344172, 0.00542109,
       0.01053745, 0.06489182, 0.43026134, 0.163037  , 0.43616458,
       0.28486902, 0.03255995, 0.03238094, 0.04445824, 0.03566094,
       0.06601522, 0.16922272, 0.04980671, 0.3328733 , 0.06104916,
       0.05893806, 0.46594754, 0.03097609, 0.04030006, 0.06015721,
       0.53487232, 0.04071863, 0.06168009, 0.11122742, 0.08196001,
       0.01993154, 0.10627866, 0.15087859, 0.11734231, 0.02120531,
       0.01385732, 0.03173418, 0.09477098, 0.02827014, 0.03836701,
       0.27857556, 0.12418693, 0.12221106, 0.04793684, 0.04090848,
       0.13827488, 0.03893776, 0.1326741 , 0.03260836, 0.6463494 ,
       0.00910436, 0.22745655, 0.05646022, 0.01969718, 0.26194051,
       0.02211241, 0.20206698, 0.01754894, 0.07832758, 0.02790215,
       0.01618954, 0.78817813, 0.64553365, 0.01656839, 0.01464643,
       0.10580674, 0.06724881, 0.15241969, 0.0395077 , 0.03595544,
       0.27055459, 0.048559  , 0.03147699, 0.02406163, 0.09538952,
       0.10801235, 0.03988821, 0.01180424, 0.10228077, 0.07832578,
       0.19563571, 0.09921359, 0.14558197, 0.3509562 , 0.04911867,
       0.01627257, 0.06960421, 0.02351786, 0.43194364, 0.17156908,
       0.09666199, 0.0964838 , 0.07290888, 0.10154421, 0.02399111,
       0.01279825, 0.04581037, 0.08977752, 0.0199468 , 0.47846409,
       0.34611938, 0.03987192, 0.09084002, 0.01405575, 0.30742459,
       0.23304362, 0.05274617, 0.09472132, 0.04277442, 0.31198323,
       0.00795841, 0.02666308, 0.085968  , 0.03528642, 0.02622175,
       0.02538835, 0.04530958, 0.05973832, 0.03684824, 0.01747743,
       0.58256   , 0.02864361, 0.01445424, 0.01186826, 0.02650442,
       0.09369662, 0.11888662, 0.09856531, 0.04113311, 0.00789302,
       0.01529209, 0.14899197, 0.06558167, 0.06557512, 0.02071221,
       0.65308933, 0.10368269, 0.02749549, 0.09335614, 0.03263812,
       0.03170512, 0.04491514, 0.05916472, 0.06870738, 0.02219793,
       0.0866664 , 0.47605238, 0.02414193, 0.46642854, 0.01656688,
       0.02046819, 0.37943494, 0.13260038, 0.18214444, 0.24567048,
       0.0436164 , 0.59278935, 0.02447349, 0.0286909 , 0.0382651 ,
       0.06470705, 0.02979536, 0.00692023, 0.16369582, 0.07856428,
       0.07100748, 0.56247281, 0.03638145, 0.02518334, 0.00844928,
       0.02540058, 0.18186022, 0.09250332, 0.01026159, 0.02174545,
       0.06558029, 0.01879966, 0.00966503, 0.01976213, 0.13435057,
       0.03836199, 0.08304683, 0.02203012, 0.10150625, 0.03920103,
       0.93585879, 0.02482084, 0.06226055, 0.03645044, 0.10039103,
       0.11646381, 0.04557017, 0.75573332, 0.91154279, 0.04769006,
       0.04733544, 0.02964189, 0.7885589 , 0.43024522, 0.03300932,
       0.06040192, 0.06412458, 0.02632947, 0.02535282, 0.04474566,
       0.13414424, 0.01166364, 0.02218189, 0.06285828, 0.05168179,
       0.01675308, 0.89477368, 0.27949185, 0.03863143, 0.01666389,
       0.05809863, 0.05325329, 0.11826941, 0.1107342 , 0.03767409,
       0.14686539, 0.0172388 , 0.05698083, 0.31969106, 0.0930973 ,
       0.06830588, 0.02259608, 0.15037036, 0.67841337, 0.0801523 ,
       0.02497329, 0.04072172, 0.05500474, 0.73551099, 0.01957128,
       0.01054606, 0.10351308, 0.32435373, 0.19862808, 0.40788368,
       0.2427252 , 0.34969875, 0.02609643, 0.00955827, 0.09943282,
       0.14942169, 0.56717232, 0.00767614, 0.10494135, 0.11936124,
       0.04241026, 0.05399626, 0.02582495, 0.20085375, 0.0830049 ,
       0.29747761, 0.23179645, 0.07222898, 0.36182717, 0.06348351,
       0.0858059 , 0.1862702 , 0.3538499 , 0.21297715, 0.18716443,
       0.24351682, 0.05325851, 0.17874453, 0.11308971, 0.03576376,
       0.07883719, 0.25101811, 0.04001943, 0.01282527, 0.08682665,
       0.03581176, 0.06687399, 0.15883902, 0.04510026, 0.01858372,
       0.05073877, 0.41508651, 0.11321376, 0.03305205, 0.38129809,
       0.36736179, 0.01621049, 0.10050029, 0.25347477, 0.06685757,
       0.05106788, 0.00897326, 0.03656863, 0.06389918, 0.08964635,
       0.27975497, 0.35988305, 0.15481282, 0.89048196, 0.04001814,
       0.02160252, 0.07948274, 0.11626501, 0.01889831, 0.14432418,
       0.02283414, 0.01561195, 0.25060679, 0.07057778, 0.04727651,
       0.04460291, 0.18075356, 0.2740618 , 0.13798309, 0.66373135,
       0.02159793, 0.05183374, 0.03988369, 0.06865036, 0.07871566,
       0.13135124, 0.1568136 , 0.16215702, 0.13862968, 0.01569679,
       0.0129244 , 0.05478365, 0.0486278 , 0.1144906 , 0.04352979,
       0.03322787, 0.05116029, 0.08546843, 0.50579885, 0.01017468,
       0.133452  , 0.07389633, 0.17382683, 0.0235137 , 0.0142517 ,
       0.1255411 , 0.04698614, 0.06625692, 0.04715255, 0.08316495,
       0.03478421, 0.70277621, 0.02014312, 0.0817045 , 0.31821214,
       0.06868932, 0.02790948, 0.01629069, 0.0270607 , 0.03766953,
       0.08633758, 0.27173688, 0.41691176, 0.02871213, 0.12920727,
       0.01515885, 0.02739378, 0.29928589, 0.47885676, 0.11228764,
       0.03974723, 0.0113255 , 0.02871476, 0.38010216, 0.06587964,
       0.08126375, 0.06473045, 0.11419906, 0.26251827, 0.01614001,
       0.01505166, 0.16209944, 0.54593046, 0.03592122, 0.75555449,
       0.06266694, 0.0991809 , 0.33391849, 0.57730019, 0.44042646,
       0.01805374, 0.01373657, 0.01576032, 0.39563391, 0.01936872,
       0.20441937, 0.04794751, 0.01979695, 0.01194234, 0.14391897,
       0.69193863, 0.12656123, 0.0117118 , 0.03593616, 0.27821843,
       0.11206511, 0.06574734, 0.25227518, 0.0398901 , 0.23406959,
       0.02053429, 0.06688824, 0.17204218, 0.03265467, 0.01488776,
       0.12143108, 0.01774386, 0.24350414, 0.8089561 , 0.54982627,
       0.01590913, 0.05085535, 0.0168767 , 0.81738163, 0.08801846,
       0.02546102, 0.00881093, 0.31451925, 0.097211  , 0.11234222,
       0.05934957, 0.02318888, 0.21973591, 0.02758534, 0.34113832,
       0.04904412, 0.04374088, 0.01988259, 0.47697194, 0.02186363,
       0.01699469, 0.01160839, 0.02943107, 0.31902684, 0.01485983,
       0.10104783, 0.16481965, 0.02328537, 0.08443078, 0.51665603,
       0.01257137, 0.08007702, 0.0430657 , 0.22721083, 0.04484989,
       0.01312224, 0.00507831, 0.01762421, 0.01020559, 0.05914471,
       0.01842688, 0.05927862, 0.04022417, 0.0900575 , 0.2926333 ,
       0.20922644, 0.03490391, 0.04692426, 0.04574514, 0.0772586 ,
       0.40814726, 0.03312129, 0.06002726, 0.18029074, 0.01358779,
       0.09612003, 0.03545778, 0.58260189, 0.10474247, 0.01115504,
       0.04202226, 0.02162452, 0.02887606, 0.07872726, 0.22623148,
       0.03293049, 0.02781701, 0.28809525, 0.20366529, 0.01741157,
       0.00859836, 0.0440061 , 0.06836906, 0.07069311, 0.07363994,
       0.06174078, 0.03217781, 0.01893488, 0.01346554, 0.07445146,
       0.0633805 , 0.51808534, 0.08857312, 0.01599047, 0.05926959,
       0.0428131 , 0.22170044, 0.06658668, 0.29712283, 0.03884816,
       0.25004409, 0.13965399, 0.02677777, 0.01837024, 0.66919819,
       0.02368848, 0.01570316, 0.03692068, 0.16587551, 0.31988488,
       0.26575807, 0.43211731, 0.13492654, 0.07157055, 0.26898563,
       0.0174682 , 0.01009089, 0.01744475, 0.45906989, 0.05289721,
       0.28407711, 0.04279965, 0.01098548, 0.03051864, 0.06001117,
       0.01950022, 0.02680717, 0.04250696, 0.01526645, 0.23318112,
       0.0106002 , 0.0393415 , 0.03076207, 0.0410179 , 0.15994975,
       0.01683182, 0.58370349, 0.01091585])

In [104]:
auc = roc_auc_score(y_test, y_pred_proba)
print("roc-auc : ",auc)

roc-auc :  0.8234335680793671

# テスト

In [105]:
submit_x = df_test.drop(columns=["id"])
submit_x[cat_cols] = submit_x[cat_cols].astype('category')

In [106]:
submit_x

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,Designation,MonthlyIncome,customer_info
0,４８歳,Self Enquiry,2,13分,Small Business,Male,1.0,4.0,Super De|uxe,3.0,7,0,3,AVP,496950.0,結婚済み 車所持 子供なし
1,30代,Self Enquiry,2,12分,Small Business,Ｆｅｍａｌｅ,1.0,4.0,Standard,3.0,4,1,3,Senior Manager,月収30.0万円,結婚済み、車未所持、子供なし
2,25歳,Self Enquiry,1,540秒,Salaried,Female,1.0,4.0,Basic,3.0,1,0,3,Executive,月収26.0万円,離婚済み、自動車未所有、子供なし
3,21歳,Company Invited,2,420秒,Salaried,Male,1.0,4.0,Basic,4.0,1,0,3,Senior Manager,259875.0,離婚済み、自動車所有、子供なし
4,41歳,Company Invited,1,7分,Salaried,MALE,1.0,4.0,Basic,3.0,1,0,4,Executive,268830.0,独身/車所持／子供なし
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3484,41歳,Company Invited,1,14分,Small Business,Female,1.0,3.0,Basic,3.0,2,0,4,Executive,261840.0,結婚済み/車なし／子供無し
3485,44歳,Company Invited,1,35分,Salaried,Male,3.0,5.0,Deluxe,3.0,3,0,3,Manager,349770.0,結婚済み、自家用車あり、子供1人
3486,24歳,Self Enquiry,2,21分,Small Business,male,2.0,3.0,basic,3.0,2,0,3,Executive,月収27.0万円,独身、車未所持、子供なし
3487,25歳,Self Enquiry,1,9分,Small Business,MALE,2.0,3.0,Basic,3.0,2,0,3,Executive,272430.0,結婚済み、車未所持、こども1人
3488,44才,Self Enquiry,1,480秒,Small Business,female,4.0,4.0,Deluxe,3.0,5,0,1,Manager,411795.0,未婚 車なし 子供3人

In [109]:
test_pred = model.predict(submit_x)
test_pred

array([0.1402353 , 0.08601121, 0.58385454, ..., 0.41911692, 0.27872769,
       0.00780031], shape=(3489,))

# 提出ファイル、submit_x（テスト）生成

In [111]:
submission = pd.DataFrame({
    'id': df_test['id'],
    'y': test_pred
})

submission.to_csv('submission.csv', index=False, header=False)
submit_x.to_csv("submit_x_x_x_x_x_x.csv", index=False, header=False)

submission

        id         y
0     3489  0.140235
1     3490  0.086011
2     3491  0.583855
3     3492  0.543870
4     3493  0.379375
...    ...       ...
3484  6973  0.227484
3485  6974  0.013546
3486  6975  0.419117
3487  6976  0.278728
3488  6977  0.007800

[3489 rows x 2 columns]