In [43]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.style
import seaborn as sns
import unicodedata

In [44]:
df = df = pd.read_csv("train.csv")

In [45]:
df['Gender']

0         male
1         Male
2       Female
3       female
4       female
         ...
3484      Male
3485      Male
3486    FEMALE
3487      Male
3488      male
Name: Gender, Length: 3489, dtype: object

In [46]:
df['Gender'].value_counts()

Gender
Male       1226
Female      739
male        468
female      266
MALE        183
Ｍａｌｅ        126
Fe Male     109
FEMALE       99
Ｆｅｍａｌｅ       89
ｍａｌｅ         43
ｆｅｍａｌｅ       36
fe male      29
FE MALE      23
ＭＡＬＥ         18
Ｆｅ　Ｍａｌｅ      15
ＦＥＭＡＬＥ       13
ｆｅ　ｍａｌｅ       6
ＦＥ　ＭＡＬＥ       1
Name: count, dtype: int64

In [47]:
df['Gender'] = df['Gender'].str.replace(' ', '')
df['Gender'] = df['Gender'].str.lower().apply(lambda x: unicodedata.normalize('NFKC', str(x)))
df['Gender'] = df['Gender'].str.normalize('NFKC').str.lower().map({'male': 0, 'female': 1})

In [48]:
df['Gender'].value_counts()

Gender
0.0    2064
1.0    1403
Name: count, dtype: int64

０：男性
１：女性